### ISSUE TITLE
1.20.4 Version?

### ISSUE THREAD

**Issue by Jack-Chronicle** [Blatko1/flamepot#1]
If any of the currently available downloads on Modrinth are compatible with 1.20.4, they don't seem to be working
If they're not (more likely) then could you add a port to it? Would love to have this datapack to use

**Comment by Blatko1** [comment]
I will upload a version which supports 1.20.4 in an hour or less. Have you tried this [version](https://modrinth.com/datapack/flamepots/version/1.0.0) on 1.20.4, because it works for me, but you just need to manually enable it with the `datapack` command while in game.

**Comment by Jack-Chronicle** [comment]
That one seems to work, not sure how I missed that

**Comment by Blatko1** [comment]
[Here](https://modrinth.com/datapack/flamepots/version/Dt48e67d) it is if you want the officially supported version.
